Implementacion ninemanga
corp-0/manga-scrap pull request #1
Opened 2021-09-04 22:04 UTC by kanroot

2021-09-06 10:51 UTC, corp-0 requested changes

2021-09-06 10:51 UTC, corp-0 commented on __main__.py
> +from manga_scrap.proveedores.nineMangaNet import NineMangaNet
Limpia el contenido de este archivo

2021-09-06 10:51 UTC, corp-0 commented on manga_scrap/modelos.py
> +    Representacion de un unico genero para un manga
```suggestion
    Representacion de un único genero para un manga
```

2021-09-06 10:51 UTC, corp-0 commented on manga_scrap/modelos.py
> +    generos: List[Genero]
esto hace que los géneros sean obligatorios. Es esa la intención?

2021-09-06 10:51 UTC, corp-0 commented on manga_scrap/modelos.py
> +        total = 0
queda mejor contar los géneros usando ``len``
```suggestion
        return len(self.generos)
```

2021-09-06 10:51 UTC, corp-0 commented on manga_scrap/proveedores/nineMangaNet.py
> +
Elimina la línea de más
```suggestion
```

2021-09-06 10:51 UTC, corp-0 commented on manga_scrap/proveedores/proveedor.py
> +    def obtener_generos(self, preview: MangaPreview):
Esto obliga a todos los proveedores a implementar este método. Es intencional? Además puede que sea bueno agregar los generos al modelo de Preview directamente.

2021-09-06 10:51 UTC, corp-0 commented on manga_scrap/proveedores/prueba.py
> +    def obtener_generos(self, manga: Manga):
Este método no tiene la misma cabecera que el que está implementando. Los tipos del parámetro son diferentes.

2021-09-06 10:51 UTC, corp-0 commented on tests/test_proveedor.py
> +    def test_generos_anidadas_al_manga(self):
este test no tiene ninguna prueba (``self.assertx()``)

2021-09-07 22:20 UTC, kanroot commented on manga_scrap/modelos.py
> +    generos: List[Genero]
Los géneros deben ser obligatorios en tanto no quieras mostrar hentai en la app, sin los géneros nos sería imposible filtrar por lo menos para la presentación de la app.

2021-09-07 22:22 UTC, kanroot commented on manga_scrap/proveedores/proveedor.py
> +    def obtener_generos(self, preview: MangaPreview):
Creo que sería mejor implementar los géneros en el mangapreview, pero disminuye la velocidad de la consulta y la construcción del objeto mangapreview.

2021-09-07 22:23 UTC, kanroot commented on manga_scrap/proveedores/prueba.py
> +    def obtener_generos(self, manga: Manga):
error mio, veamos como queremos construir los generos si en la preview o en el manga como tal.

2021-09-07 22:26 UTC, kanroot commented on tests/test_proveedor.py
> +    def test_generos_anidadas_al_manga(self):
Tendré que consultarte como implementar ese test.

2021-09-07 22:26 UTC, corp-0 commented on manga_scrap/modelos.py
> +    generos: List[Genero]
pueden ser opcionales. No sé si todos los proveedores tendrán género.

2021-09-07 22:27 UTC, corp-0 commented on manga_scrap/proveedores/proveedor.py
> +    def obtener_generos(self, preview: MangaPreview):
De todos modos pretendemos guardar el catálogo en disco como caché para la consulta

2021-09-07 22:29 UTC, corp-0 commented on manga_scrap/modelos.py
> +        for c in self.generos:
dejaste el resto del cuerpo de la propiedad.

2021-09-07 22:34 UTC, kanroot commented on manga_scrap/modelos.py
> +    generos: List[Genero]
tendríamos que revisar en otros proveedores que sean "escrapeables" y ver si tienen o no genero para confirmar su existencia como un elemento común, en mi experiencia como lector siempre los mangas tienen a lo menos un género o podriamos darle un valor por defecto en caso contrario.

2021-09-07 22:34 UTC, kanroot commented on manga_scrap/proveedores/proveedor.py
> +    def obtener_generos(self, preview: MangaPreview):
buena solución.

2021-09-07 22:37 UTC, kanroot commented on __main__.py
> +from manga_scrap.proveedores.nineMangaNet import NineMangaNet
10-4

2021-09-07 23:50 UTC, corp-0 approved these changes

2021-09-07 23:51 UTC, merged